#!/usr/bin/bash
# shellcheck shell=bash
# shellcheck source=/dev/null

. /etc/s6-overlay/bin/set-contenv

# This script is responsible for setting up the environment for the Calibre Web Automated add-on.
# It reads configuration options, prepares necessary directories, and ensures that the application has access to the required paths.
readonly CONFIG_PATH=/config
readonly INGEST_PATH=/cwa-book-ingest
readonly CALIBRE_LIBRARY_PATH=/calibre-library
readonly CALIBRE_PLUGINS_PATH=/config/.config/calibre/plugins

# Source bashio to make its functions available
. /usr/lib/bashio/bashio.sh

# Function to stop the script from running to debug the environment
debug_script() {
    if [ "$(bashio::config 'debug_mode')" == "true" ]; then
        bashio::log.warning "Debug mode enabled, stopping script execution for debugging"
        sleep infinity
    fi
}

# Stop the script from continuing to debug the environment
debug_script

# Function to set environment variables based on add-on configuration
set_env_var_from_config() {
    local config_key="${1}"
    local env_name="${2}"
    local config_value

    config_value=$(bashio::config "${config_key}")
    if [ -z "${config_value}" ]; then
        bashio::log.warning "Configuration value for ${config_key} is empty"
        return
    fi
    echo -n "${config_value}" > "/etc/s6-overlay/env/${env_name}"
}

# Function to resolve a path from the add-on configuration and ensure it is a valid absolute path
resolve_path() {
    local config_key="$1"
    local resolved_path

    resolved_path=$(realpath "/$(bashio::config "${config_key}")") || {
        bashio::log.fatal "Failed to resolve ${config_key}: $(bashio::config "${config_key}")"
        bashio::exit.nok
    }

    printf '%s' "${resolved_path}"
}

# Function to map a host directory to the application's expected path using a symbolic link
map_path() {
    local mapped_path="${1}"
    local app_path="${2}"

    # Ensure the host-mapped directory exists (e.g., /share/my_folder)
    if ! bashio::fs.directory_exists "${mapped_path}"; then
        bashio::log.info "Creating directory ${mapped_path}"
        mkdir -p "${mapped_path}"
    fi
    # If the mapped path is the same as the app path, no need to create a symlink
    if [ "${mapped_path}" == "${app_path}" ]; then
        bashio::log.debug "Mapped path ${mapped_path} is the same as app path ${app_path}, skipping symlink creation"
        return
    fi
    # If the app's default directory exists and isn't a link, move it or remove it
    if [ -d "${app_path}" ] && [ ! -L "${app_path}" ]; then
        bashio::log.debug "Removing existing internal directory to make room for symlink"
        rm -rf "${app_path}"
    fi
    # Create the link
    ln -s "${mapped_path}" "${app_path}"
    bashio::log.success "Successfully mapped ${app_path} to ${mapped_path}"
}

# Main execution starts here
bashio::log.info "Configuring environment..."

set_env_var_from_config 'hard_cover_token' 'HARDCOVER_TOKEN'
set_env_var_from_config 'network_share_mode' 'NETWORK_SHARE_MODE'


bashio::log.info "Mapping paths..."

map_path "$(resolve_path 'config_path')" "${CONFIG_PATH}"
map_path "$(resolve_path 'ingest_path')" "${INGEST_PATH}"
map_path "$(resolve_path 'calibre_library_path')" "${CALIBRE_LIBRARY_PATH}"
map_path "$(resolve_path 'calibre_plugins_path')" "${CALIBRE_PLUGINS_PATH}"


bashio::log.info "Environment setup complete."

# Stop the script from continuing to debug the environment
debug_script